//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.DataAnnotations;

namespace Aula04Out24.Models {
    public partial class Cadastro {
        public int ID { get; set; }
        public string NomeFull { get; set; }

        [Required(ErrorMessage = "O CPF é obrigatório.")]
        public string CPF { get; set; }
        public string Cargo { get; set; }
        public string Email { get; set; }

        [Required(ErrorMessage = "A senha é obrigatória.")]
        [StringLength(8, MinimumLength = 8, ErrorMessage = "A senha deve ter 8 caracteres.")]
        public string Senha { get; set; }
    }
}
