//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aula04Out24.Models {
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Fornecedores {
        public int Id { get; set; }
        public string Nome { get; set; }

        public string TipoFornecimento { get; set; }

        public string Descricao { get; set; }

        public string Telefone { get; set; }

        public string Email { get; set; }

        public string CNPJ { get; set; }
        public string Bairro { get; set; }
        public string Numero { get; set; }
        public string Rua { get; set; }
    }
}